local export_classes = {
  ["manual-lib-source"] = true,
  ["manual-project-source"] = true,
  ["manual-project-test"] = true,
  ["manual-project-script"] = true,
  ["manual-project-config"] = true,
}

local manual_vars = {}

local function stringify(value)
  return pandoc.utils.stringify(value)
end

local function capture_env_vars()
  local env_map = {
    project_name = "RSE_MANUAL_VAR_PROJECT_NAME",
    project_package = "RSE_MANUAL_VAR_PROJECT_PACKAGE",
    manual_type = "RSE_MANUAL_VAR_MANUAL_TYPE",
    project_dir = "RSE_MANUAL_VAR_PROJECT_DIR",
    package_root = "RSE_MANUAL_VAR_PACKAGE_ROOT",
    manual_root = "RSE_MANUAL_VAR_MANUAL_ROOT",
  }

  for key, env_name in pairs(env_map) do
    local value = os.getenv(env_name)
    if value ~= nil and value ~= "" then
      manual_vars[key] = value
    end
  end
end

local function capture_manual_vars(meta)
  if meta.manual == nil then
    return
  end

  for key, value in pairs(meta.manual) do
    manual_vars[key] = stringify(value)
  end
end

local function has_export_class(el)
  local matched = nil

  for class_name, _ in pairs(export_classes) do
    if el.classes:includes(class_name) then
      if matched ~= nil then
        error("Manual export block must include exactly one export class.")
      end
      matched = class_name
    end
  end

  return matched
end

local function find_code_blocks(blocks, found)
  found = found or {}

  for _, block in ipairs(blocks) do
    if block.t == "CodeBlock" then
      table.insert(found, block)
    elseif block.content ~= nil then
      find_code_blocks(block.content, found)
    end
  end

  return found
end

local function dirname(path)
  return path:match("(.+)/[^/]+$")
end

local function shell_quote(path)
  return "'" .. string.gsub(path, "'", "'\\''") .. "'"
end

local function mkdir_p(dir)
  if dir ~= nil and dir ~= "" then
    os.execute("mkdir -p " .. shell_quote(dir))
  end
end

local function file_exists(path)
  local handle = io.open(path, "r")
  if handle ~= nil then
    handle:close()
    return true
  end
  return false
end

local function read_file(path)
  local handle = io.open(path, "r")
  if handle == nil then
    return nil
  end
  local content = handle:read("*a")
  handle:close()
  return content
end

local function has_generated_header(path)
  local content = read_file(path)
  if content == nil then
    return false
  end
  return string.find(content, "Generated by rse%-manual", 1, false) ~= nil
end

local function render_template_variables(text)
  return string.gsub(text, "{{%s*([%a_][%w_]*)%s*}}", function(key)
    return manual_vars[key] or "{{ " .. key .. " }}"
  end)
end

local function header_for(language, source)
  if language == "lua" or language == "sql" then
    return "-- Generated by rse-manual.\n"
      .. "-- Source: " .. source .. "\n"
      .. "-- Do not edit directly unless you intend to stop using the manual as source of truth.\n\n"
  end

  if language == "markdown" or language == "md" then
    return "<!-- Generated by rse-manual. -->\n"
      .. "<!-- Source: " .. source .. " -->\n"
      .. "<!-- Do not edit directly unless you intend to stop using the manual as source of truth. -->\n\n"
  end

  return "# Generated by rse-manual.\n"
    .. "# Source: " .. source .. "\n"
    .. "# Do not edit directly unless you intend to stop using the manual as source of truth.\n\n"
end

local function write_file(path, content)
  mkdir_p(dirname(path))
  local handle = io.open(path, "w")
  if handle == nil then
    error("Could not open target for writing: " .. path)
  end
  handle:write(content)
  handle:close()
end

local function chmod_if_requested(path, mode)
  if mode == "0755" then
    os.execute("chmod 0755 " .. shell_quote(path))
  end
end

function Meta(meta)
  capture_manual_vars(meta)
  capture_env_vars()
  return meta
end

function Div(el)
  local export_class = has_export_class(el)
  if export_class == nil then
    return el
  end

  local inflating = os.getenv("RSE_MANUAL_EXPORT") == "1"
  if not inflating then
    return el
  end

  local target = el.attributes["file"]
  if target == nil or target == "" then
    error("Manual export block is missing file attribute.")
  end

  local code_blocks = find_code_blocks(el.content)
  if #code_blocks ~= 1 then
    error("Manual export block must contain exactly one code block: " .. target)
  end

  capture_env_vars()

  local code_block = code_blocks[1]
  local language = code_block.classes[1] or ""
  local source = quarto.doc.input_file or "unknown-source"
  local force = os.getenv("RSE_MANUAL_FORCE") == "1"
  local check = os.getenv("RSE_MANUAL_CHECK") == "1"

  local rendered_target = render_template_variables(target)
  local rendered_body = render_template_variables(code_block.text)
  local output = header_for(language, source) .. rendered_body

  if string.sub(output, -1) ~= "\n" then
    output = output .. "\n"
  end

  local existing = read_file(rendered_target)

  if file_exists(rendered_target) and not has_generated_header(rendered_target) and not force then
    error("Refusing to overwrite non-generated file: " .. rendered_target)
  end

  if check then
    if existing == output then
      quarto.log.output("[rse-manual] unchanged " .. rendered_target)
    else
      quarto.log.output("[rse-manual] would write " .. rendered_target)
    end
    return el
  end

  if existing ~= output then
    write_file(rendered_target, output)
    chmod_if_requested(rendered_target, el.attributes["mode"])
    quarto.log.output("[rse-manual] wrote " .. rendered_target)
  else
    quarto.log.output("[rse-manual] unchanged " .. rendered_target)
  end

  return el
end
