# Generated by rse-manual.
# Source: /Users/tit420/projects/QuartoManual/index.qmd
# Do not edit directly unless you intend to stop using the manual as source of truth.

from __future__ import annotations

from pathlib import Path
import subprocess


def expect_file(path: str | Path) -> Path:
    """Assert that a file exists and return it as a Path."""
    path = Path(path)
    assert path.exists(), f"Expected path to exist: {path}"
    assert path.is_file(), f"Expected file: {path}"
    return path


def expect_dir(path: str | Path) -> Path:
    """Assert that a directory exists and return it as a Path."""
    path = Path(path)
    assert path.exists(), f"Expected path to exist: {path}"
    assert path.is_dir(), f"Expected directory: {path}"
    return path


def expect_command_succeeds(command: list[str]) -> None:
    """Assert that a command exits successfully."""
    result = subprocess.run(
        command,
        check=False,
        capture_output=True,
        text=True,
    )

    assert result.returncode == 0, (
        "Command failed: "
        + " ".join(command)
        + "\nSTDOUT:\n"
        + result.stdout
        + "\nSTDERR:\n"
        + result.stderr
    )
