# Generated by rse-manual.
# Source: /Users/tit420/projects/QuartoManual/index.qmd
# Do not edit directly unless you intend to stop using the manual as source of truth.

#!/usr/bin/env bash
set -euo pipefail

project_dir="{{ project_dir }}"

echo "Checking project directory: ${project_dir}"

test -d "${project_dir}"
test -d "${project_dir}/config"
test -d "${project_dir}/src" || mkdir -p "${project_dir}/src"
test -d "${project_dir}/tests" || mkdir -p "${project_dir}/tests"

echo "Project scaffold exists."
