-- Generated by rse-manual.
-- Source: /Users/tit420/projects/QuartoManual/index.qmd
-- Do not edit directly unless you intend to stop using the manual as source of truth.

select
  '{{ project_name }}' as project_name,
  '{{ project_package }}' as project_package,
  '{{ manual_type }}' as manual_type;
