# Generated by rse-manual.
# Source: /Users/tit420/projects/QuartoManual/index.qmd
# Do not edit directly unless you intend to stop using the manual as source of truth.

from pathlib import Path

from {{ project_package }}.contract import ProjectContract


def test_project_contract_discovers_project():
    project = ProjectContract.discover()

    assert project.project_name == "{{ project_name }}"
    assert project.project_package == "{{ project_package }}"
    assert project.project_dir.name == Path("{{ project_dir }}").name


def test_project_contract_paths_are_named():
    project = ProjectContract.discover()

    assert project.src_dir.name == "src"
    assert project.tests_dir.name == "tests"
    assert project.config_dir.name == "config"
