# Generated by rse-manual.
# Source: /Users/tit420/projects/QuartoManual/index.qmd
# Do not edit directly unless you intend to stop using the manual as source of truth.

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class ProjectContract:
    """Minimal project contract generated by a Quarto Manual page."""

    project_name: str
    project_package: str
    project_dir: Path

    @classmethod
    def discover(cls) -> "ProjectContract":
        return cls(
            project_name="{{ project_name }}",
            project_package="{{ project_package }}",
            project_dir=Path("{{ project_dir }}").resolve(),
        )

    @property
    def src_dir(self) -> Path:
        return self.project_dir / "src"

    @property
    def tests_dir(self) -> Path:
        return self.project_dir / "tests"

    @property
    def config_dir(self) -> Path:
        return self.project_dir / "config"
